-- MySQL Script generated by MySQL Workbench
-- Tue Feb 26 20:25:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDD_Projet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDD_Projet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDD_Projet` DEFAULT CHARACTER SET utf8 ;
USE `BDD_Projet` ;

-- -----------------------------------------------------
-- Table `BDD_Projet`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDD_Projet`.`Utilisateur` (
  `id_Utilisateur` INT NOT NULL AUTO_INCREMENT,
  `Pseudo` VARCHAR(80) NULL,
  `Mot_de_passe` VARCHAR(80) NULL,
  `Email` VARCHAR(80) NULL,
  PRIMARY KEY (`id_Utilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDD_Projet`.`Theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDD_Projet`.`Theme` (
  `id_Theme` INT NOT NULL AUTO_INCREMENT,
  `Nom_theme` VARCHAR(80) NULL,
  `Libelle_theme` LONGTEXT NULL,
  `Etat_theme` TINYINT(1) NULL,
  PRIMARY KEY (`id_Theme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDD_Projet`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDD_Projet`.`Question` (
  `id_Question` INT NOT NULL AUTO_INCREMENT,
  `Libelle_question` LONGTEXT NULL,
  `Niveau` ENUM('Niv_1', 'Niv_2', 'Niv_3', 'Niv_4', 'Niv_5') NULL,
  `Etat_question` TINYINT(1) NULL,
  `Theme_id_Theme` INT NOT NULL,
  PRIMARY KEY (`id_Question`, `Theme_id_Theme`),
  CONSTRAINT `fk_Question_Theme1`
    FOREIGN KEY (`Theme_id_Theme`)
    REFERENCES `BDD_Projet`.`Theme` (`id_Theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `BDD_Projet`.`Reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDD_Projet`.`Reponse` (
  `id_Reponse_question` INT NOT NULL AUTO_INCREMENT,
  `Reponse_correct` TINYINT(1) NULL,
  `Score` INT NULL,
  `Question_id_Question` INT NOT NULL,
  `Utilisateur_id_Utilisateur` INT NOT NULL,
  PRIMARY KEY (`id_Reponse_question`, `Question_id_Question`, `Utilisateur_id_Utilisateur`),
  CONSTRAINT `fk_Reponse_Question1`
    FOREIGN KEY (`Question_id_Question`)
    REFERENCES `BDD_Projet`.`Question` (`id_Question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reponse_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `BDD_Projet`.`Utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 1;




-- -----------------------------------------------------
-- Table `BDD_Projet`.`Mot_cle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDD_Projet`.`Mot_cle` (
  `Mot` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Mot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDD_Projet`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDD_Projet`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(80) NULL,
  `password` VARCHAR(80) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDD_Projet`.`Score_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDD_Projet`.`Score_utilisateur` (
  `idScore_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `Score_total` INT NULL,
  `Utilisateur_id_Utilisateur` INT NOT NULL,
  PRIMARY KEY (`idScore_utilisateur`, `Utilisateur_id_Utilisateur`),
  CONSTRAINT `fk_Score_utilisateur_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `BDD_Projet`.`Utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `BDD_Projet`.`Score_theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDD_Projet`.`Score_theme` (
  `Theme_id_Theme` INT NOT NULL,
  `Utilisateur_id_Utilisateur` INT NOT NULL,
  `Score_theme` INT NULL,
  PRIMARY KEY (`Theme_id_Theme`, `Utilisateur_id_Utilisateur`),
  CONSTRAINT `fk_Theme_has_Utilisateur_Theme1`
    FOREIGN KEY (`Theme_id_Theme`)
    REFERENCES `BDD_Projet`.`Theme` (`id_Theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Theme_has_Utilisateur_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `BDD_Projet`.`Utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `BDD_Projet`.`Proposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDD_Projet`.`Proposition` (
  `Theme_id_Theme` INT NOT NULL,
  `Utilisateur_id_Utilisateur` INT NULL,
  `Question_id_Question` INT NOT NULL,
  `Question_Theme_id_Theme` INT NOT NULL,
  `Question_proposition_user` LONGTEXT NULL,
  `Theme_proposition_user` LONGTEXT NULL,
  `Etat_proposition` TINYINT(1) NULL,
  PRIMARY KEY (`Theme_id_Theme`, `Utilisateur_id_Utilisateur`, `Question_id_Question`, `Question_Theme_id_Theme`),
  CONSTRAINT `fk_Theme_has_Utilisateur_Theme2`
    FOREIGN KEY (`Theme_id_Theme`)
    REFERENCES `BDD_Projet`.`Theme` (`id_Theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Theme_has_Utilisateur_Utilisateur2`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `BDD_Projet`.`Utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Theme_has_Utilisateur_Question1`
    FOREIGN KEY (`Question_id_Question` , `Question_Theme_id_Theme`)
    REFERENCES `BDD_Projet`.`Question` (`id_Question` , `Theme_id_Theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `BDD_Projet`.`Possede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDD_Projet`.`Possede` (
  `Mot_cle_Mot` VARCHAR(255) NOT NULL,
  `Theme_id_Theme` INT NOT NULL,
  PRIMARY KEY (`Mot_cle_Mot`, `Theme_id_Theme`),
  CONSTRAINT `fk_Mot_cle_has_Theme_Mot_cle1`
    FOREIGN KEY (`Mot_cle_Mot`)
    REFERENCES `BDD_Projet`.`Mot_cle` (`Mot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mot_cle_has_Theme_Theme1`
    FOREIGN KEY (`Theme_id_Theme`)
    REFERENCES `BDD_Projet`.`Theme` (`id_Theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
